#!/bin/sh
set -e

if [ -z "$1" ]; then
  echo "Usage:"
  echo "    kubectl use <context> [namespace]"
  echo
  exit 1
fi

kubectl config use "$1"

if [ -z "$2" ]; then
  exit 0
fi

kubectl config set-context --current --namespace="$2" > /dev/null
echo "Switched to namespace \"$2\"."
