#!/bin/sh
set -e

if [ -z "$1" ] || [ "${1::1}" = "-" ]; then
  echo "Usage:"
  echo "    kubectl use namespace"
  echo "    kubectl use context"
  echo "    kubectl use context namespace"
  echo
  exit 1
fi

for context in $(kubectl config get-contexts -o name); do
  if [ "$1" = "$context" ]; then
    new_context="$1"
    break
  fi
done

if [ -n "$new_context" ]; then
  kubectl config use "$1"
  if [ -n "$2" ]; then
    new_namespace="$2"
  fi
else
  if [ -n "$2" ]; then
    echo "Can not swith context \"$1\"."
    exit 1
  fi
  new_namespace="$1"
fi

if [ -n "$new_namespace" ]; then
  kubectl config set-context --current --namespace="$new_namespace" > /dev/null
  echo "Switched to namespace \"$new_namespace\"."
fi
